-- Add input_tokens and output_tokens fields to builds table
-- These fields will track AI model usage for each build

-- Add input_tokens column (number of input tokens used by AI model)
ALTER TABLE builds ADD COLUMN input_tokens INTEGER;

-- Add output_tokens column (number of output tokens generated by AI model)  
ALTER TABLE builds ADD COLUMN output_tokens INTEGER;

-- Add indexes for performance on token fields (useful for usage analytics)
CREATE INDEX idx_builds_input_tokens ON builds(input_tokens) WHERE input_tokens IS NOT NULL;
CREATE INDEX idx_builds_output_tokens ON builds(output_tokens) WHERE output_tokens IS NOT NULL;

-- Add comments to explain the new fields
COMMENT ON COLUMN builds.input_tokens IS 'Number of input tokens consumed by AI model during generation';
COMMENT ON COLUMN builds.output_tokens IS 'Number of output tokens generated by AI model during generation';