-- Add token usage and duration metrics to prompts table
-- This will track AI API usage for cost analysis and performance monitoring

-- Add input_tokens column
ALTER TABLE prompts ADD COLUMN input_tokens INTEGER;

-- Add output_tokens column
ALTER TABLE prompts ADD COLUMN output_tokens INTEGER;

-- Add duration_ms column (milliseconds)
ALTER TABLE prompts ADD COLUMN duration_ms INTEGER;

-- Add comments to explain the columns
COMMENT ON COLUMN prompts.input_tokens IS 'Number of input tokens consumed by the AI API for this prompt';
COMMENT ON COLUMN prompts.output_tokens IS 'Number of output tokens generated by the AI API for this prompt';
COMMENT ON COLUMN prompts.duration_ms IS 'Total time in milliseconds for the AI API call to complete';
