-- Create inspo_type enum for categorizing inspiration types
CREATE TYPE inspo_type AS ENUM ('LANDING_PAGE');

-- Create inspo table for storing inspiration content
CREATE TABLE inspo (
  id UUID PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  name VARCHAR NOT NULL,
  type inspo_type NOT NULL DEFAULT 'LANDING_PAGE',
  mime_type VARCHAR NOT NULL,
  file_name VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  modified_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Add comment for table documentation
COMMENT ON TABLE inspo IS 'Stores inspiration content like landing page screenshots';
COMMENT ON COLUMN inspo.name IS 'Display name of the inspiration item (e.g., company name)';
COMMENT ON COLUMN inspo.type IS 'Type of inspiration: LANDING_PAGE';
COMMENT ON COLUMN inspo.mime_type IS 'MIME type of the file (e.g., image/png, image/jpeg)';
COMMENT ON COLUMN inspo.file_name IS 'Filename without path (e.g., shuttle.png)';

-- Create index on type for efficient filtering
CREATE INDEX idx_inspo_type ON inspo(type);

-- Enable RLS
ALTER TABLE inspo ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users only (never allow public access)
CREATE POLICY "Allow authenticated read access" ON inspo
  FOR SELECT
  TO authenticated
  USING (true);

-- Insert all 606 landing page images
INSERT INTO inspo (name, type, mime_type, file_name) VALUES
('Shuttle', 'LANDING_PAGE', 'image/png', 'shuttle.png'),
('Cycle', 'LANDING_PAGE', 'image/png', 'cycle.png'),
('Chargetrip', 'LANDING_PAGE', 'image/png', 'chargetrip.png'),
('Mobbin', 'LANDING_PAGE', 'image/png', 'mobbin.png'),
('Ballpark', 'LANDING_PAGE', 'image/png', 'ballpark.png'),
('Visitors', 'LANDING_PAGE', 'image/png', 'visitors.png'),
('Revolut X', 'LANDING_PAGE', 'image/png', 'revolut-x.png'),
('Aave', 'LANDING_PAGE', 'image/png', 'aave.png'),
('Framer', 'LANDING_PAGE', 'image/png', 'framer.png'),
('Vooma', 'LANDING_PAGE', 'image/png', 'vooma.png'),
('Gladia', 'LANDING_PAGE', 'image/png', 'gladia.png'),
('Framer Commerce', 'LANDING_PAGE', 'image/png', 'framer-commerce.png'),
('Holocene', 'LANDING_PAGE', 'image/png', 'holocene.png'),
('Summation', 'LANDING_PAGE', 'image/png', 'summation.png'),
('Lattice', 'LANDING_PAGE', 'image/png', 'lattice.png'),
('David AI', 'LANDING_PAGE', 'image/png', 'david-ai.png'),
('Humble', 'LANDING_PAGE', 'image/png', 'humble.png'),
('Lens', 'LANDING_PAGE', 'image/png', 'lens.png'),
('Claude', 'LANDING_PAGE', 'image/png', 'claude.png'),
('Superhuman', 'LANDING_PAGE', 'image/png', 'superhuman.png'),
('Affinity', 'LANDING_PAGE', 'image/png', 'affinity.png'),
('Firsty', 'LANDING_PAGE', 'image/png', 'firsty.png'),
('ChatGPT Atlas', 'LANDING_PAGE', 'image/png', 'chatgpt-atlas.png'),
('Qatch up', 'LANDING_PAGE', 'image/png', 'qatch-up.png'),
('Atlius', 'LANDING_PAGE', 'image/png', 'atlius.png'),
('Peec AI', 'LANDING_PAGE', 'image/png', 'peec-ai.png'),
('Origin', 'LANDING_PAGE', 'image/png', 'origin.png'),
('Reducto', 'LANDING_PAGE', 'image/png', 'reducto.png'),
('Ditto', 'LANDING_PAGE', 'image/png', 'ditto.png'),
('Cloudflare Workers', 'LANDING_PAGE', 'image/png', 'cloudflare-workers.png'),
('Duna', 'LANDING_PAGE', 'image/png', 'duna.png'),
('FeedSpring', 'LANDING_PAGE', 'image/png', 'feedspring.png'),
('Wynde', 'LANDING_PAGE', 'image/png', 'wynde.png'),
('Cursor', 'LANDING_PAGE', 'image/png', 'cursor.png'),
('Brainfish', 'LANDING_PAGE', 'image/png', 'brainfish.png'),
('Wispr Flow', 'LANDING_PAGE', 'image/png', 'wispr-flow.png'),
('Gigaml', 'LANDING_PAGE', 'image/png', 'gigaml.png'),
('Craft', 'LANDING_PAGE', 'image/png', 'craft.png'),
('Dayos', 'LANDING_PAGE', 'image/png', 'dayos.png'),
('Lemon.io', 'LANDING_PAGE', 'image/png', 'lemon-io.png'),
('Cofounder', 'LANDING_PAGE', 'image/png', 'cofounder.png'),
('Ballpark', 'LANDING_PAGE', 'image/png', 'ballpark.png'),
('Superpower', 'LANDING_PAGE', 'image/png', 'superpower.png'),
('Operate', 'LANDING_PAGE', 'image/png', 'operate.png'),
('Laravel Nigthwatch', 'LANDING_PAGE', 'image/png', 'laravel-nigthwatch.png'),
('Maggie App', 'LANDING_PAGE', 'image/png', 'maggie-app.png'),
('Current', 'LANDING_PAGE', 'image/png', 'current.png'),
('Cluely', 'LANDING_PAGE', 'image/png', 'cluely.png'),
('7shifts', 'LANDING_PAGE', 'image/png', '7shifts.png'),
('Firecrawl', 'LANDING_PAGE', 'image/png', 'firecrawl.png'),
('Paradigm', 'LANDING_PAGE', 'image/png', 'paradigm.png'),
('Trispy', 'LANDING_PAGE', 'image/png', 'trispy.png'),
('Endex', 'LANDING_PAGE', 'image/png', 'endex.png'),
('Mollie', 'LANDING_PAGE', 'image/png', 'mollie.png'),
('Rogo', 'LANDING_PAGE', 'image/png', 'rogo.png'),
('Clutch', 'LANDING_PAGE', 'image/png', 'clutch.png'),
('Miter', 'LANDING_PAGE', 'image/png', 'miter.png'),
('SafetyKit', 'LANDING_PAGE', 'image/png', 'safetykit.png'),
('Speakeasy', 'LANDING_PAGE', 'image/png', 'speakeasy.png'),
('Kinhive', 'LANDING_PAGE', 'image/png', 'kinhive.png'),
('Wone', 'LANDING_PAGE', 'image/png', 'wone.png'),
('Say Briefly', 'LANDING_PAGE', 'image/png', 'say-briefly.png'),
('Paraform', 'LANDING_PAGE', 'image/png', 'paraform.png'),
('TOP', 'LANDING_PAGE', 'image/png', 'top.png'),
('LottieFiles', 'LANDING_PAGE', 'image/png', 'lottiefiles.png'),
('Bonsai', 'LANDING_PAGE', 'image/png', 'bonsai.png'),
('Relato', 'LANDING_PAGE', 'image/png', 'relato.png'),
('Three Tools', 'LANDING_PAGE', 'image/png', 'three-tools.png'),
('Zapier', 'LANDING_PAGE', 'image/png', 'zapier.png'),
('Resend', 'LANDING_PAGE', 'image/png', 'resend.png'),
('Aboard', 'LANDING_PAGE', 'image/png', 'aboard.png'),
('Orbi', 'LANDING_PAGE', 'image/png', 'orbi.png'),
('Intercom Suite', 'LANDING_PAGE', 'image/png', 'intercom-suite.png'),
('Outseta', 'LANDING_PAGE', 'image/png', 'outseta.png'),
('xAI', 'LANDING_PAGE', 'image/png', 'xai.png'),
('Portrait', 'LANDING_PAGE', 'image/png', 'portrait.png'),
('Fin.', 'LANDING_PAGE', 'image/png', 'fin.png'),
('Delphi', 'LANDING_PAGE', 'image/png', 'delphi.png'),
('Content Square', 'LANDING_PAGE', 'image/png', 'content-square.png'),
('Sanity', 'LANDING_PAGE', 'image/png', 'sanity.png'),
('Lemni', 'LANDING_PAGE', 'image/png', 'lemni.png'),
('Portal', 'LANDING_PAGE', 'image/png', 'portal.png'),
('Slash', 'LANDING_PAGE', 'image/png', 'slash.png'),
('Gamma', 'LANDING_PAGE', 'image/png', 'gamma.png'),
('Blackalgo', 'LANDING_PAGE', 'image/png', 'blackalgo.png'),
('Debtfindr', 'LANDING_PAGE', 'image/png', 'debtfindr.png'),
('Framer Events', 'LANDING_PAGE', 'image/png', 'framer-events.png'),
('Realm', 'LANDING_PAGE', 'image/png', 'realm.png'),
('Valdera', 'LANDING_PAGE', 'image/png', 'valdera.png'),
('Tars', 'LANDING_PAGE', 'image/png', 'tars.png'),
('Cartesia', 'LANDING_PAGE', 'image/png', 'cartesia.png'),
('Routable', 'LANDING_PAGE', 'image/png', 'routable.png'),
('Front', 'LANDING_PAGE', 'image/png', 'front.png'),
('Maybe', 'LANDING_PAGE', 'image/png', 'maybe.png'),
('Jumpshare', 'LANDING_PAGE', 'image/png', 'jumpshare.png'),
('Monarch', 'LANDING_PAGE', 'image/png', 'monarch.png'),
('Lynq', 'LANDING_PAGE', 'image/png', 'lynq.png'),
('Basecamp', 'LANDING_PAGE', 'image/png', 'basecamp.png'),
('Reveni', 'LANDING_PAGE', 'image/png', 'reveni.png'),
('Jitter', 'LANDING_PAGE', 'image/png', 'jitter.png'),
('Ko-fi', 'LANDING_PAGE', 'image/png', 'ko-fi.png'),
('Missive', 'LANDING_PAGE', 'image/png', 'missive.png'),
('Abode', 'LANDING_PAGE', 'image/png', 'abode.png'),
('Deel', 'LANDING_PAGE', 'image/png', 'deel.png'),
('Dovetail', 'LANDING_PAGE', 'image/png', 'dovetail.png'),
('Folk', 'LANDING_PAGE', 'image/png', 'folk.png'),
('Ada', 'LANDING_PAGE', 'image/png', 'ada.png'),
('Wittl', 'LANDING_PAGE', 'image/png', 'wittl.png'),
('Incident.io', 'LANDING_PAGE', 'image/png', 'incident-io.png'),
('Applied Labs', 'LANDING_PAGE', 'image/png', 'applied-labs.png'),
('Travelwise', 'LANDING_PAGE', 'image/png', 'travelwise.png'),
('Clay', 'LANDING_PAGE', 'image/png', 'clay.png'),
('Joi Planner', 'LANDING_PAGE', 'image/png', 'joi-planner.png'),
('Seline', 'LANDING_PAGE', 'image/png', 'seline.png'),
('Runway', 'LANDING_PAGE', 'image/png', 'runway.png'),
('Frankli', 'LANDING_PAGE', 'image/png', 'frankli.png'),
('Profound', 'LANDING_PAGE', 'image/png', 'profound.png'),
('Tiempo', 'LANDING_PAGE', 'image/png', 'tiempo.png'),
('Laravel Cloud', 'LANDING_PAGE', 'image/png', 'laravel-cloud.png'),
('Finta', 'LANDING_PAGE', 'image/png', 'finta.png'),
('Osmo', 'LANDING_PAGE', 'image/png', 'osmo.png'),
('Medusa', 'LANDING_PAGE', 'image/png', 'medusa.png'),
('Flourish Commerce', 'LANDING_PAGE', 'image/png', 'flourish-commerce.png'),
('Typeform', 'LANDING_PAGE', 'image/png', 'typeform.png'),
('Fey', 'LANDING_PAGE', 'image/png', 'fey.png'),
('V7', 'LANDING_PAGE', 'image/png', 'v7.png'),
('Equals', 'LANDING_PAGE', 'image/png', 'equals.png'),
('Mintlify', 'LANDING_PAGE', 'image/png', 'mintlify.png'),
('Sevalla', 'LANDING_PAGE', 'image/png', 'sevalla.png'),
('Oxide', 'LANDING_PAGE', 'image/png', 'oxide.png'),
('Statamic', 'LANDING_PAGE', 'image/png', 'statamic.png'),
('Frame.io', 'LANDING_PAGE', 'image/png', 'frame-io.png'),
('Neon', 'LANDING_PAGE', 'image/png', 'neon.png'),
('Sora', 'LANDING_PAGE', 'image/png', 'sora.png'),
('Scribe', 'LANDING_PAGE', 'image/png', 'scribe.png'),
('Keel', 'LANDING_PAGE', 'image/png', 'keel.png'),
('Exactly.ai', 'LANDING_PAGE', 'image/png', 'exactly-ai.png'),
('Aria', 'LANDING_PAGE', 'image/png', 'aria.png'),
('Webflow', 'LANDING_PAGE', 'image/png', 'webflow.png'),
('&Open', 'LANDING_PAGE', 'image/png', 'open.png'),
('Notion', 'LANDING_PAGE', 'image/png', 'notion.png'),
('AlignUI', 'LANDING_PAGE', 'image/png', 'alignui.png'),
('Kit', 'LANDING_PAGE', 'image/png', 'kit.png'),
('Peek Insights', 'LANDING_PAGE', 'image/png', 'peek-insights.png'),
('Owner', 'LANDING_PAGE', 'image/png', 'owner.png'),
('Ramp', 'LANDING_PAGE', 'image/png', 'ramp.png'),
('Attio', 'LANDING_PAGE', 'image/png', 'attio.png'),
('Cal.com', 'LANDING_PAGE', 'image/png', 'cal-com.png'),
('Recraft', 'LANDING_PAGE', 'image/png', 'recraft.png'),
('Backlog', 'LANDING_PAGE', 'image/png', 'backlog.png'),
('Granola', 'LANDING_PAGE', 'image/png', 'granola.png'),
('Loops', 'LANDING_PAGE', 'image/png', 'loops.png'),
('Notion Mail', 'LANDING_PAGE', 'image/png', 'notion-mail.png'),
('Hex', 'LANDING_PAGE', 'image/png', 'hex.png'),
('Podia', 'LANDING_PAGE', 'image/png', 'podia.png'),
('Mparticle', 'LANDING_PAGE', 'image/png', 'mparticle.png'),
('August Health', 'LANDING_PAGE', 'image/png', 'august-health.png'),
('DreamCut', 'LANDING_PAGE', 'image/png', 'dreamcut.png'),
('Kin', 'LANDING_PAGE', 'image/png', 'kin.png'),
('Stacker', 'LANDING_PAGE', 'image/png', 'stacker.png'),
('Notion AI', 'LANDING_PAGE', 'image/png', 'notion-ai.png'),
('Sketch', 'LANDING_PAGE', 'image/png', 'sketch.png'),
('Flighty', 'LANDING_PAGE', 'image/png', 'flighty.png'),
('Descript', 'LANDING_PAGE', 'image/png', 'descript.png'),
('Amplemarket', 'LANDING_PAGE', 'image/png', 'amplemarket.png'),
('Shopify', 'LANDING_PAGE', 'image/png', 'shopify.png'),
('Empathy', 'LANDING_PAGE', 'image/png', 'empathy.png'),
('Kota', 'LANDING_PAGE', 'image/png', 'kota.png'),
('Nucleo', 'LANDING_PAGE', 'image/png', 'nucleo.png'),
('ChatGPT', 'LANDING_PAGE', 'image/png', 'chatgpt.png'),
('Volta', 'LANDING_PAGE', 'image/png', 'volta.png'),
('Chipper Business', 'LANDING_PAGE', 'image/png', 'chipper-business.png'),
('Prismic', 'LANDING_PAGE', 'image/png', 'prismic.png'),
('Fly.io', 'LANDING_PAGE', 'image/png', 'fly-io.png'),
('Supabase', 'LANDING_PAGE', 'image/png', 'supabase.png'),
('Endless Tools', 'LANDING_PAGE', 'image/png', 'endless-tools.png'),
('Ycode', 'LANDING_PAGE', 'image/png', 'ycode.png'),
('Campsite', 'LANDING_PAGE', 'image/png', 'campsite.png'),
('Tedy', 'LANDING_PAGE', 'image/png', 'tedy.png'),
('uMake', 'LANDING_PAGE', 'image/png', 'umake.png'),
('Lunacy', 'LANDING_PAGE', 'image/png', 'lunacy.png'),
('Titan', 'LANDING_PAGE', 'image/png', 'titan.png'),
('Buzzabout', 'LANDING_PAGE', 'image/png', 'buzzabout.png'),
('Quite Nice', 'LANDING_PAGE', 'image/png', 'quite-nice.png'),
('Artboard Studio', 'LANDING_PAGE', 'image/png', 'artboard-studio.png'),
('Clerk', 'LANDING_PAGE', 'image/png', 'clerk.png'),
('Fable', 'LANDING_PAGE', 'image/png', 'fable.png'),
('Tbh', 'LANDING_PAGE', 'image/png', 'tbh.png'),
('STUDIO', 'LANDING_PAGE', 'image/png', 'studio.png'),
('Fiverr', 'LANDING_PAGE', 'image/png', 'fiverr.png'),
('Figma', 'LANDING_PAGE', 'image/png', 'figma.png'),
('Qonto', 'LANDING_PAGE', 'image/png', 'qonto.png'),
('SaveDay', 'LANDING_PAGE', 'image/png', 'saveday.png'),
('Guild', 'LANDING_PAGE', 'image/png', 'guild.png'),
('Liveblocks', 'LANDING_PAGE', 'image/png', 'liveblocks.png'),
('Linear', 'LANDING_PAGE', 'image/png', 'linear.png'),
('Huly', 'LANDING_PAGE', 'image/png', 'huly.png'),
('ModernLoop', 'LANDING_PAGE', 'image/png', 'modernloop.png'),
('Crayo AI', 'LANDING_PAGE', 'image/png', 'crayo-ai.png'),
('Assemble', 'LANDING_PAGE', 'image/png', 'assemble.png'),
('Limitless', 'LANDING_PAGE', 'image/png', 'limitless.png'),
('Propbinder', 'LANDING_PAGE', 'image/png', 'propbinder.png'),
('Evervault', 'LANDING_PAGE', 'image/png', 'evervault.png'),
('Data.to.design', 'LANDING_PAGE', 'image/png', 'data-to-design.png'),
('Auth0', 'LANDING_PAGE', 'image/png', 'auth0.png'),
('Canopy', 'LANDING_PAGE', 'image/png', 'canopy.png'),
('Agora', 'LANDING_PAGE', 'image/png', 'agora.png'),
('SavvyCal', 'LANDING_PAGE', 'image/png', 'savvycal.png'),
('Upwork', 'LANDING_PAGE', 'image/png', 'upwork.png'),
('ListenUp!', 'LANDING_PAGE', 'image/png', 'listenup.png'),
('Raycast', 'LANDING_PAGE', 'image/png', 'raycast.png'),
('Mercury', 'LANDING_PAGE', 'image/png', 'mercury.png'),
('Unsplash+', 'LANDING_PAGE', 'image/png', 'unsplash.png'),
('Buy Me a Coffee', 'LANDING_PAGE', 'image/png', 'buy-me-a-coffee.png'),
('#paid', 'LANDING_PAGE', 'image/png', 'paid.png'),
('Finvest', 'LANDING_PAGE', 'image/png', 'finvest.png'),
('Critter', 'LANDING_PAGE', 'image/png', 'critter.png'),
('Family', 'LANDING_PAGE', 'image/png', 'family.png'),
('Storytale', 'LANDING_PAGE', 'image/png', 'storytale.png'),
('Tailscale', 'LANDING_PAGE', 'image/png', 'tailscale.png'),
('Tola', 'LANDING_PAGE', 'image/png', 'tola.png'),
('GitButler', 'LANDING_PAGE', 'image/png', 'gitbutler.png'),
('Bytebot', 'LANDING_PAGE', 'image/png', 'bytebot.png'),
('Quillow', 'LANDING_PAGE', 'image/png', 'quillow.png'),
('Epidemic Sound', 'LANDING_PAGE', 'image/png', 'epidemic-sound.png'),
('Wealthsimple', 'LANDING_PAGE', 'image/png', 'wealthsimple.png'),
('Musho.ai', 'LANDING_PAGE', 'image/png', 'musho-ai.png'),
('Status', 'LANDING_PAGE', 'image/png', 'status.png'),
('Evernote', 'LANDING_PAGE', 'image/png', 'evernote.png'),
('Pivot', 'LANDING_PAGE', 'image/png', 'pivot.png'),
('Lovi', 'LANDING_PAGE', 'image/png', 'lovi.png'),
('Astrafi', 'LANDING_PAGE', 'image/png', 'astrafi.png'),
('Vesto', 'LANDING_PAGE', 'image/png', 'vesto.png'),
('Supahub', 'LANDING_PAGE', 'image/png', 'supahub.png'),
('Coda', 'LANDING_PAGE', 'image/png', 'coda.png'),
('Anygood', 'LANDING_PAGE', 'image/png', 'anygood.png'),
('Peerlist', 'LANDING_PAGE', 'image/png', 'peerlist.png'),
('Tomorro', 'LANDING_PAGE', 'image/png', 'tomorro.png'),
('Relume Library', 'LANDING_PAGE', 'image/png', 'relume-library.png'),
('Fathom', 'LANDING_PAGE', 'image/png', 'fathom.png'),
('Refrakt', 'LANDING_PAGE', 'image/png', 'refrakt.png'),
('Garner', 'LANDING_PAGE', 'image/png', 'garner.png'),
('Orum', 'LANDING_PAGE', 'image/png', 'orum.png'),
('Dropbox', 'LANDING_PAGE', 'image/png', 'dropbox.png'),
('Notion Calendar', 'LANDING_PAGE', 'image/png', 'notion-calendar.png'),
('Pipe', 'LANDING_PAGE', 'image/png', 'pipe.png'),
('Increase', 'LANDING_PAGE', 'image/png', 'increase.png'),
('Compound', 'LANDING_PAGE', 'image/png', 'compound.png'),
('Tandym', 'LANDING_PAGE', 'image/png', 'tandym.png'),
('Opus', 'LANDING_PAGE', 'image/png', 'opus.png'),
('Going', 'LANDING_PAGE', 'image/png', 'going.png'),
('Focal', 'LANDING_PAGE', 'image/png', 'focal.png'),
('Rise', 'LANDING_PAGE', 'image/png', 'rise.png'),
('Superlist', 'LANDING_PAGE', 'image/png', 'superlist.png'),
('Slater', 'LANDING_PAGE', 'image/png', 'slater.png'),
('Kikin', 'LANDING_PAGE', 'image/png', 'kikin.png'),
('AuthKit', 'LANDING_PAGE', 'image/png', 'authkit.png'),
('Steep', 'LANDING_PAGE', 'image/png', 'steep.png'),
('Wiza', 'LANDING_PAGE', 'image/png', 'wiza.png'),
('FlowMapp', 'LANDING_PAGE', 'image/png', 'flowmapp.png'),
('AngelList', 'LANDING_PAGE', 'image/png', 'angellist.png'),
('GitHub', 'LANDING_PAGE', 'image/png', 'github.png'),
('Cardinal', 'LANDING_PAGE', 'image/png', 'cardinal.png'),
('Ozone', 'LANDING_PAGE', 'image/png', 'ozone.png'),
('Stripe Startups', 'LANDING_PAGE', 'image/png', 'stripe-startups.png'),
('Retool', 'LANDING_PAGE', 'image/png', 'retool.png'),
('Clay', 'LANDING_PAGE', 'image/png', 'clay.png'),
('Puck', 'LANDING_PAGE', 'image/png', 'puck.png'),
('Vercel', 'LANDING_PAGE', 'image/png', 'vercel.png'),
('GSAP', 'LANDING_PAGE', 'image/png', 'gsap.png'),
('Welcome', 'LANDING_PAGE', 'image/png', 'welcome.png'),
('Bio Link', 'LANDING_PAGE', 'image/png', 'bio-link.png'),
('Acuity:scheduling', 'LANDING_PAGE', 'image/png', 'acuity-scheduling.png'),
('PostHog', 'LANDING_PAGE', 'image/png', 'posthog.png'),
('Pelago', 'LANDING_PAGE', 'image/png', 'pelago.png'),
('Todoist', 'LANDING_PAGE', 'image/png', 'todoist.png'),
('Miro', 'LANDING_PAGE', 'image/png', 'miro.png'),
('Kaizen', 'LANDING_PAGE', 'image/png', 'kaizen.png'),
('Rig.dev', 'LANDING_PAGE', 'image/png', 'rig-dev.png'),
('Gitness', 'LANDING_PAGE', 'image/png', 'gitness.png'),
('Dimension', 'LANDING_PAGE', 'image/png', 'dimension.png'),
('Fable', 'LANDING_PAGE', 'image/png', 'fable.png'),
('Osome', 'LANDING_PAGE', 'image/png', 'osome.png'),
('Shape', 'LANDING_PAGE', 'image/png', 'shape.png'),
('Dribbble', 'LANDING_PAGE', 'image/png', 'dribbble.png'),
('observIQ', 'LANDING_PAGE', 'image/png', 'observiq.png'),
('AngelList Relay', 'LANDING_PAGE', 'image/png', 'angellist-relay.png'),
('Mercu', 'LANDING_PAGE', 'image/png', 'mercu.png'),
('HeyFriends', 'LANDING_PAGE', 'image/png', 'heyfriends.png'),
('BlockWallet', 'LANDING_PAGE', 'image/png', 'blockwallet.png'),
('Homerun', 'LANDING_PAGE', 'image/png', 'homerun.png'),
('Rainforest', 'LANDING_PAGE', 'image/png', 'rainforest.png'),
('Bolt', 'LANDING_PAGE', 'image/png', 'bolt.png'),
('Proven', 'LANDING_PAGE', 'image/png', 'proven.png'),
('Remote', 'LANDING_PAGE', 'image/png', 'remote.png'),
('Config', 'LANDING_PAGE', 'image/png', 'config.png'),
('Magic Beans', 'LANDING_PAGE', 'image/png', 'magic-beans.png'),
('FramerAuth', 'LANDING_PAGE', 'image/png', 'framerauth.png'),
('Readymag', 'LANDING_PAGE', 'image/png', 'readymag.png'),
('Glide', 'LANDING_PAGE', 'image/png', 'glide.png'),
('Secfi', 'LANDING_PAGE', 'image/png', 'secfi.png'),
('Imagifly', 'LANDING_PAGE', 'image/png', 'imagifly.png'),
('Middesk', 'LANDING_PAGE', 'image/png', 'middesk.png'),
('Bandit', 'LANDING_PAGE', 'image/png', 'bandit.png'),
('mymind', 'LANDING_PAGE', 'image/png', 'mymind.png'),
('Geckoboard', 'LANDING_PAGE', 'image/png', 'geckoboard.png'),
('Hopscotch', 'LANDING_PAGE', 'image/png', 'hopscotch.png'),
('Diagram', 'LANDING_PAGE', 'image/png', 'diagram.png'),
('House of Pitch', 'LANDING_PAGE', 'image/png', 'house-of-pitch.png'),
('Aaply', 'LANDING_PAGE', 'image/png', 'aaply.png'),
('Specify', 'LANDING_PAGE', 'image/png', 'specify.png'),
('Feedly', 'LANDING_PAGE', 'image/png', 'feedly.png'),
('Mixpanel', 'LANDING_PAGE', 'image/png', 'mixpanel.png'),
('STUDIO AI', 'LANDING_PAGE', 'image/png', 'studio-ai.png'),
('Bento', 'LANDING_PAGE', 'image/png', 'bento.png'),
('Literal', 'LANDING_PAGE', 'image/png', 'literal.png'),
('Ruul', 'LANDING_PAGE', 'image/png', 'ruul.png'),
('Reflect', 'LANDING_PAGE', 'image/png', 'reflect.png'),
('Pera', 'LANDING_PAGE', 'image/png', 'pera.png'),
('Synthesized', 'LANDING_PAGE', 'image/png', 'synthesized.png'),
('Surfe', 'LANDING_PAGE', 'image/png', 'surfe.png'),
('Spline AI', 'LANDING_PAGE', 'image/png', 'spline-ai.png'),
('FigJam', 'LANDING_PAGE', 'image/png', 'figjam.png'),
('Supportninja', 'LANDING_PAGE', 'image/png', 'supportninja.png'),
('Plutio', 'LANDING_PAGE', 'image/png', 'plutio.png'),
('Twingate', 'LANDING_PAGE', 'image/png', 'twingate.png'),
('Onfolk', 'LANDING_PAGE', 'image/png', 'onfolk.png'),
('Postcards', 'LANDING_PAGE', 'image/png', 'postcards.png'),
('Relume Ipsum', 'LANDING_PAGE', 'image/png', 'relume-ipsum.png'),
('uConnect', 'LANDING_PAGE', 'image/png', 'uconnect.png'),
('Swag', 'LANDING_PAGE', 'image/png', 'swag.png'),
('Anron', 'LANDING_PAGE', 'image/png', 'anron.png'),
('CodeSandbox', 'LANDING_PAGE', 'image/png', 'codesandbox.png'),
('Winden', 'LANDING_PAGE', 'image/png', 'winden.png'),
('BePrepared', 'LANDING_PAGE', 'image/png', 'beprepared.png'),
('Wise', 'LANDING_PAGE', 'image/png', 'wise.png'),
('Chronicle', 'LANDING_PAGE', 'image/png', 'chronicle.png'),
('Bridge', 'LANDING_PAGE', 'image/png', 'bridge.png'),
('Whelp', 'LANDING_PAGE', 'image/png', 'whelp.png'),
('Trullion', 'LANDING_PAGE', 'image/png', 'trullion.png'),
('Wope', 'LANDING_PAGE', 'image/png', 'wope.png'),
('Dock', 'LANDING_PAGE', 'image/png', 'dock.png'),
('Fold', 'LANDING_PAGE', 'image/png', 'fold.png'),
('Butter', 'LANDING_PAGE', 'image/png', 'butter.png'),
('Magician', 'LANDING_PAGE', 'image/png', 'magician.png'),
('Nuxt', 'LANDING_PAGE', 'image/png', 'nuxt.png'),
('Highnote', 'LANDING_PAGE', 'image/png', 'highnote.png'),
('Slite', 'LANDING_PAGE', 'image/png', 'slite.png'),
('Thursday', 'LANDING_PAGE', 'image/png', 'thursday.png'),
('Groove', 'LANDING_PAGE', 'image/png', 'groove.png'),
('InVision Freehand', 'LANDING_PAGE', 'image/png', 'invision-freehand.png'),
('Ready', 'LANDING_PAGE', 'image/png', 'ready.png'),
('Junip', 'LANDING_PAGE', 'image/png', 'junip.png'),
('Mode', 'LANDING_PAGE', 'image/png', 'mode.png'),
('Mural', 'LANDING_PAGE', 'image/png', 'mural.png'),
('Better Stack', 'LANDING_PAGE', 'image/png', 'better-stack.png'),
('Decipad', 'LANDING_PAGE', 'image/png', 'decipad.png'),
('Payload CMS', 'LANDING_PAGE', 'image/png', 'payload-cms.png'),
('PlanetScale', 'LANDING_PAGE', 'image/png', 'planetscale.png'),
('Railway', 'LANDING_PAGE', 'image/png', 'railway.png'),
('The Cape Agency', 'LANDING_PAGE', 'image/png', 'the-cape-agency.png'),
('Formcarry', 'LANDING_PAGE', 'image/png', 'formcarry.png'),
('Stellar', 'LANDING_PAGE', 'image/png', 'stellar.png'),
('Typefully', 'LANDING_PAGE', 'image/png', 'typefully.png'),
('Lemon Squeezy', 'LANDING_PAGE', 'image/png', 'lemon-squeezy.png'),
('Xref', 'LANDING_PAGE', 'image/png', 'xref.png'),
('Tracky', 'LANDING_PAGE', 'image/png', 'tracky.png'),
('Prevalent AI', 'LANDING_PAGE', 'image/png', 'prevalent-ai.png'),
('Overflow', 'LANDING_PAGE', 'image/png', 'overflow.png'),
('Next.js', 'LANDING_PAGE', 'image/png', 'next-js.png'),
('Startup', 'LANDING_PAGE', 'image/png', 'startup.png'),
('RPC Fast', 'LANDING_PAGE', 'image/png', 'rpc-fast.png'),
('Carta', 'LANDING_PAGE', 'image/png', 'carta.png'),
('Pipedrive', 'LANDING_PAGE', 'image/png', 'pipedrive.png'),
('Bloom', 'LANDING_PAGE', 'image/png', 'bloom.png'),
('Primer', 'LANDING_PAGE', 'image/png', 'primer.png'),
('Wealthsimple Spend', 'LANDING_PAGE', 'image/png', 'wealthsimple-spend.png'),
('Unloan', 'LANDING_PAGE', 'image/png', 'unloan.png'),
('Acorns', 'LANDING_PAGE', 'image/png', 'acorns.png'),
('Mailchimp', 'LANDING_PAGE', 'image/png', 'mailchimp.png'),
('Cult', 'LANDING_PAGE', 'image/png', 'cult.png'),
('Atomus', 'LANDING_PAGE', 'image/png', 'atomus.png'),
('Metronome', 'LANDING_PAGE', 'image/png', 'metronome.png'),
('Landing', 'LANDING_PAGE', 'image/png', 'landing.png'),
('Modern Life', 'LANDING_PAGE', 'image/png', 'modern-life.png'),
('Substack', 'LANDING_PAGE', 'image/png', 'substack.png'),
('Dribbble Pro', 'LANDING_PAGE', 'image/png', 'dribbble-pro.png'),
('Setpoint', 'LANDING_PAGE', 'image/png', 'setpoint.png'),
('DatoCMS', 'LANDING_PAGE', 'image/png', 'datocms.png'),
('Fibery', 'LANDING_PAGE', 'image/png', 'fibery.png'),
('Settle', 'LANDING_PAGE', 'image/png', 'settle.png'),
('Eduphoria', 'LANDING_PAGE', 'image/png', 'eduphoria.png'),
('PandaDoc', 'LANDING_PAGE', 'image/png', 'pandadoc.png'),
('Toggl Hire', 'LANDING_PAGE', 'image/png', 'toggl-hire.png'),
('Gusto Wallet', 'LANDING_PAGE', 'image/png', 'gusto-wallet.png'),
('Postmark', 'LANDING_PAGE', 'image/png', 'postmark.png'),
('Spendflo', 'LANDING_PAGE', 'image/png', 'spendflo.png'),
('Appraisd', 'LANDING_PAGE', 'image/png', 'appraisd.png'),
('Revealbot', 'LANDING_PAGE', 'image/png', 'revealbot.png'),
('Walling', 'LANDING_PAGE', 'image/png', 'walling.png'),
('HeadsUp', 'LANDING_PAGE', 'image/png', 'headsup.png'),
('Hotjar', 'LANDING_PAGE', 'image/png', 'hotjar.png'),
('Nova Benefits', 'LANDING_PAGE', 'image/png', 'nova-benefits.png'),
('Lodestar', 'LANDING_PAGE', 'image/png', 'lodestar.png'),
('Haven', 'LANDING_PAGE', 'image/png', 'haven.png'),
('Linktree', 'LANDING_PAGE', 'image/png', 'linktree.png'),
('Tranch', 'LANDING_PAGE', 'image/png', 'tranch.png'),
('SellX', 'LANDING_PAGE', 'image/png', 'sellx.png'),
('WorkOS', 'LANDING_PAGE', 'image/png', 'workos.png'),
('Xolo', 'LANDING_PAGE', 'image/png', 'xolo.png'),
('Copilot', 'LANDING_PAGE', 'image/png', 'copilot.png'),
('Pulestic', 'LANDING_PAGE', 'image/png', 'pulestic.png'),
('Revolut', 'LANDING_PAGE', 'image/png', 'revolut.png'),
('Create Video', 'LANDING_PAGE', 'image/png', 'create-video.png'),
('Vivid', 'LANDING_PAGE', 'image/png', 'vivid.png'),
('Column', 'LANDING_PAGE', 'image/png', 'column.png'),
('Acadium', 'LANDING_PAGE', 'image/png', 'acadium.png'),
('Brutask', 'LANDING_PAGE', 'image/png', 'brutask.png'),
('Betterway', 'LANDING_PAGE', 'image/png', 'betterway.png'),
('Discord', 'LANDING_PAGE', 'image/png', 'discord.png'),
('Meter', 'LANDING_PAGE', 'image/png', 'meter.png'),
('Harvest', 'LANDING_PAGE', 'image/png', 'harvest.png'),
('Cequence', 'LANDING_PAGE', 'image/png', 'cequence.png'),
('Convo', 'LANDING_PAGE', 'image/png', 'convo.png'),
('WeTransfer Paper', 'LANDING_PAGE', 'image/png', 'wetransfer-paper.png'),
('Jam', 'LANDING_PAGE', 'image/png', 'jam.png'),
('Spline', 'LANDING_PAGE', 'image/png', 'spline.png'),
('Whereby', 'LANDING_PAGE', 'image/png', 'whereby.png'),
('Conductor', 'LANDING_PAGE', 'image/png', 'conductor.png'),
('Empower', 'LANDING_PAGE', 'image/png', 'empower.png'),
('QuestionScout', 'LANDING_PAGE', 'image/png', 'questionscout.png'),
('Milanote', 'LANDING_PAGE', 'image/png', 'milanote.png'),
('Cleanup.pictures', 'LANDING_PAGE', 'image/png', 'cleanup-pictures.png'),
('Ionic', 'LANDING_PAGE', 'image/png', 'ionic.png'),
('Circa', 'LANDING_PAGE', 'image/png', 'circa.png'),
('Dipsea', 'LANDING_PAGE', 'image/png', 'dipsea.png'),
('Tines', 'LANDING_PAGE', 'image/png', 'tines.png'),
('Prima HealthCredit', 'LANDING_PAGE', 'image/png', 'prima-healthcredit.png'),
('Greenbridge', 'LANDING_PAGE', 'image/png', 'greenbridge.png'),
('ScrapingBee', 'LANDING_PAGE', 'image/png', 'scrapingbee.png'),
('Attentive', 'LANDING_PAGE', 'image/png', 'attentive.png'),
('Testlio', 'LANDING_PAGE', 'image/png', 'testlio.png'),
('Maki', 'LANDING_PAGE', 'image/png', 'maki.png'),
('NetSpring', 'LANDING_PAGE', 'image/png', 'netspring.png'),
('Banky', 'LANDING_PAGE', 'image/png', 'banky.png'),
('ListAcross', 'LANDING_PAGE', 'image/png', 'listacross.png'),
('Sprout', 'LANDING_PAGE', 'image/png', 'sprout.png'),
('Nuu', 'LANDING_PAGE', 'image/png', 'nuu.png'),
('Bizzabo', 'LANDING_PAGE', 'image/png', 'bizzabo.png'),
('Gleap', 'LANDING_PAGE', 'image/png', 'gleap.png'),
('Path', 'LANDING_PAGE', 'image/png', 'path.png'),
('Abstract', 'LANDING_PAGE', 'image/png', 'abstract.png'),
('Appointlet', 'LANDING_PAGE', 'image/png', 'appointlet.png'),
('Yousign', 'LANDING_PAGE', 'image/png', 'yousign.png'),
('Ghost', 'LANDING_PAGE', 'image/png', 'ghost.png'),
('Twist', 'LANDING_PAGE', 'image/png', 'twist.png'),
('Joystream', 'LANDING_PAGE', 'image/png', 'joystream.png'),
('Ironclad', 'LANDING_PAGE', 'image/png', 'ironclad.png'),
('Circle', 'LANDING_PAGE', 'image/png', 'circle.png'),
('Armadillo', 'LANDING_PAGE', 'image/png', 'armadillo.png'),
('Neatsy', 'LANDING_PAGE', 'image/png', 'neatsy.png'),
('Sprig', 'LANDING_PAGE', 'image/png', 'sprig.png'),
('Jetty', 'LANDING_PAGE', 'image/png', 'jetty.png'),
('Ahrefs', 'LANDING_PAGE', 'image/png', 'ahrefs.png'),
('Podcorn', 'LANDING_PAGE', 'image/png', 'podcorn.png'),
('Narrative BI', 'LANDING_PAGE', 'image/png', 'narrative-bi.png'),
('MakeRoom', 'LANDING_PAGE', 'image/png', 'makeroom.png'),
('Static.app', 'LANDING_PAGE', 'image/png', 'static-app.png'),
('Oku', 'LANDING_PAGE', 'image/png', 'oku.png'),
('Proto.io', 'LANDING_PAGE', 'image/png', 'proto-io.png'),
('15five', 'LANDING_PAGE', 'image/png', '15five.png'),
('Obviously.ai', 'LANDING_PAGE', 'image/png', 'obviously-ai.png'),
('Accountancy Cloud', 'LANDING_PAGE', 'image/png', 'accountancy-cloud.png'),
('Storetasker', 'LANDING_PAGE', 'image/png', 'storetasker.png'),
('Scale', 'LANDING_PAGE', 'image/png', 'scale.png'),
('Fossa', 'LANDING_PAGE', 'image/png', 'fossa.png'),
('Join', 'LANDING_PAGE', 'image/png', 'join.png'),
('Klarna', 'LANDING_PAGE', 'image/png', 'klarna.png'),
('Short.io', 'LANDING_PAGE', 'image/png', 'short-io.png'),
('Easol', 'LANDING_PAGE', 'image/jpeg', 'easol.jpg'),
('CleanShot X', 'LANDING_PAGE', 'image/png', 'cleanshot-x.png'),
('DocSpo', 'LANDING_PAGE', 'image/jpeg', 'docspo.jpg'),
('Solarisbank', 'LANDING_PAGE', 'image/png', 'solarisbank.png'),
('Uscreen', 'LANDING_PAGE', 'image/png', 'uscreen.png'),
('Linearity', 'LANDING_PAGE', 'image/png', 'linearity.png'),
('Stripe', 'LANDING_PAGE', 'image/png', 'stripe.png'),
('Swipe', 'LANDING_PAGE', 'image/png', 'swipe.png'),
('Glyphs', 'LANDING_PAGE', 'image/png', 'glyphs.png'),
('Stark', 'LANDING_PAGE', 'image/png', 'stark.png'),
('Agorapulse', 'LANDING_PAGE', 'image/png', 'agorapulse.png'),
('Cataphract', 'LANDING_PAGE', 'image/png', 'cataphract.png'),
('Pepwork', 'LANDING_PAGE', 'image/png', 'pepwork.png'),
('Playbook', 'LANDING_PAGE', 'image/png', 'playbook.png'),
('Kitchen', 'LANDING_PAGE', 'image/png', 'kitchen.png'),
('EarlyDog', 'LANDING_PAGE', 'image/png', 'earlydog.png'),
('Optimal Workshop', 'LANDING_PAGE', 'image/png', 'optimal-workshop.png'),
('Pirsch', 'LANDING_PAGE', 'image/png', 'pirsch.png'),
('Workable', 'LANDING_PAGE', 'image/png', 'workable.png'),
('Draftbit', 'LANDING_PAGE', 'image/png', 'draftbit.png'),
('Maven', 'LANDING_PAGE', 'image/png', 'maven.png'),
('Resume.io', 'LANDING_PAGE', 'image/png', 'resume-io.png'),
('Glide', 'LANDING_PAGE', 'image/jpeg', 'glide.jpg'),
('Zendesk', 'LANDING_PAGE', 'image/png', 'zendesk.png'),
('Ternary', 'LANDING_PAGE', 'image/png', 'ternary.png'),
('Maze', 'LANDING_PAGE', 'image/png', 'maze.png'),
('Sleeknote', 'LANDING_PAGE', 'image/jpeg', 'sleeknote.jpg'),
('TabExtend', 'LANDING_PAGE', 'image/png', 'tabextend.png'),
('Prowly', 'LANDING_PAGE', 'image/png', 'prowly.png'),
('Patreon', 'LANDING_PAGE', 'image/png', 'patreon.png'),
('Shipup', 'LANDING_PAGE', 'image/png', 'shipup.png'),
('Getsafe', 'LANDING_PAGE', 'image/png', 'getsafe.png'),
('Lokalise', 'LANDING_PAGE', 'image/png', 'lokalise.png'),
('Directus', 'LANDING_PAGE', 'image/png', 'directus.png'),
('Rows', 'LANDING_PAGE', 'image/png', 'rows.png'),
('Hive Streaming', 'LANDING_PAGE', 'image/png', 'hive-streaming.png'),
('Sleepiest', 'LANDING_PAGE', 'image/jpeg', 'sleepiest.jpg'),
('Talebook', 'LANDING_PAGE', 'image/png', 'talebook.png'),
('Oscar', 'LANDING_PAGE', 'image/png', 'oscar.png'),
('Greenlist', 'LANDING_PAGE', 'image/png', 'greenlist.png'),
('Zammad', 'LANDING_PAGE', 'image/png', 'zammad.png'),
('InVision', 'LANDING_PAGE', 'image/png', 'invision.png'),
('Marqeta', 'LANDING_PAGE', 'image/png', 'marqeta.png'),
('Pitch', 'LANDING_PAGE', 'image/png', 'pitch.png'),
('Loom', 'LANDING_PAGE', 'image/png', 'loom.png'),
('Anima', 'LANDING_PAGE', 'image/png', 'anima.png'),
('Eduflow', 'LANDING_PAGE', 'image/png', 'eduflow.png'),
('Mapbox', 'LANDING_PAGE', 'image/png', 'mapbox.png'),
('Overpass', 'LANDING_PAGE', 'image/png', 'overpass.png'),
('Haptic', 'LANDING_PAGE', 'image/png', 'haptic.png'),
('Maple', 'LANDING_PAGE', 'image/png', 'maple.png'),
('Kickresume', 'LANDING_PAGE', 'image/png', 'kickresume.png'),
('Air', 'LANDING_PAGE', 'image/png', 'air.png'),
('Cognito', 'LANDING_PAGE', 'image/png', 'cognito.png'),
('OpenUnit', 'LANDING_PAGE', 'image/png', 'openunit.png'),
('Fellow', 'LANDING_PAGE', 'image/png', 'fellow.png'),
('Mailbrew', 'LANDING_PAGE', 'image/png', 'mailbrew.png'),
('Boldare Boards', 'LANDING_PAGE', 'image/png', 'boldare-boards.png'),
('Programmai', 'LANDING_PAGE', 'image/png', 'programmai.png'),
('Teachable', 'LANDING_PAGE', 'image/png', 'teachable.png'),
('Toggl', 'LANDING_PAGE', 'image/png', 'toggl.png'),
('Trustpilot', 'LANDING_PAGE', 'image/png', 'trustpilot.png'),
('Calmind', 'LANDING_PAGE', 'image/png', 'calmind.png'),
('Gusto', 'LANDING_PAGE', 'image/png', 'gusto.png'),
('Greenhouse', 'LANDING_PAGE', 'image/png', 'greenhouse.png'),
('Altrüus', 'LANDING_PAGE', 'image/png', 'altruus.png'),
('BlueReceipt', 'LANDING_PAGE', 'image/png', 'bluereceipt.png'),
('Wunderbucket', 'LANDING_PAGE', 'image/png', 'wunderbucket.png'),
('Betterlance', 'LANDING_PAGE', 'image/png', 'betterlance.png'),
('GoDaddy Studio', 'LANDING_PAGE', 'image/png', 'godaddy-studio.png'),
('Spendesk', 'LANDING_PAGE', 'image/png', 'spendesk.png'),
('Typelane', 'LANDING_PAGE', 'image/png', 'typelane.png'),
('Aircall', 'LANDING_PAGE', 'image/png', 'aircall.png'),
('Marvel Enterprise', 'LANDING_PAGE', 'image/png', 'marvel-enterprise.png'),
('Discord Nitro', 'LANDING_PAGE', 'image/png', 'discord-nitro.png'),
('Videoask', 'LANDING_PAGE', 'image/png', 'videoask.png'),
('Fiverr Workspace', 'LANDING_PAGE', 'image/png', 'fiverr-workspace.png'),
('Adoric', 'LANDING_PAGE', 'image/png', 'adoric.png'),
('Twobird', 'LANDING_PAGE', 'image/png', 'twobird.png'),
('DocSend', 'LANDING_PAGE', 'image/png', 'docsend.png'),
('Pinpoint', 'LANDING_PAGE', 'image/png', 'pinpoint.png'),
('Ruttl', 'LANDING_PAGE', 'image/png', 'ruttl.png'),
('Monese', 'LANDING_PAGE', 'image/png', 'monese.png'),
('LiveChat', 'LANDING_PAGE', 'image/png', 'livechat.png'),
('Adam Church', 'LANDING_PAGE', 'image/png', 'adam-church.png'),
('Brilliant', 'LANDING_PAGE', 'image/png', 'brilliant.png'),
('Smile.io', 'LANDING_PAGE', 'image/png', 'smile-io.png'),
('Segment', 'LANDING_PAGE', 'image/png', 'segment.png'),
('Octopus', 'LANDING_PAGE', 'image/png', 'octopus.png'),
('WeTransfer Collect', 'LANDING_PAGE', 'image/png', 'wetransfer-collect.png'),
('N26', 'LANDING_PAGE', 'image/png', 'n26.png'),
('Duffel', 'LANDING_PAGE', 'image/png', 'duffel.png'),
('Klokki', 'LANDING_PAGE', 'image/png', 'klokki.png'),
('Rise', 'LANDING_PAGE', 'image/png', 'rise.png'),
('Chargebee', 'LANDING_PAGE', 'image/png', 'chargebee.png'),
('Grammarly Business', 'LANDING_PAGE', 'image/png', 'grammarly-business.png'),
('Perdoo', 'LANDING_PAGE', 'image/png', 'perdoo.png'),
('Laravel Vapor', 'LANDING_PAGE', 'image/png', 'laravel-vapor.png'),
('SeedLegals', 'LANDING_PAGE', 'image/png', 'seedlegals.png'),
('Proof', 'LANDING_PAGE', 'image/png', 'proof.png'),
('Dropbox Business', 'LANDING_PAGE', 'image/png', 'dropbox-business.png'),
('Riot', 'LANDING_PAGE', 'image/png', 'riot.png'),
('ShipBob', 'LANDING_PAGE', 'image/png', 'shipbob.png'),
('Usersnap', 'LANDING_PAGE', 'image/png', 'usersnap.png'),
('Messagebird Inbox', 'LANDING_PAGE', 'image/png', 'messagebird-inbox.png'),
('Keap', 'LANDING_PAGE', 'image/png', 'keap.png'),
('Toggl Plan', 'LANDING_PAGE', 'image/png', 'toggl-plan.png'),
('Modulz', 'LANDING_PAGE', 'image/png', 'modulz.png'),
('Infermedica', 'LANDING_PAGE', 'image/png', 'infermedica.png'),
('Dropmark', 'LANDING_PAGE', 'image/png', 'dropmark.png'),
('Conflux', 'LANDING_PAGE', 'image/png', 'conflux.png'),
('Kepler', 'LANDING_PAGE', 'image/png', 'kepler.png'),
('Shake', 'LANDING_PAGE', 'image/png', 'shake.png'),
('Northstar', 'LANDING_PAGE', 'image/png', 'northstar.png'),
('Ballpark', 'LANDING_PAGE', 'image/png', 'ballpark.png'),
('Slate', 'LANDING_PAGE', 'image/png', 'slate.png'),
('Grammarly', 'LANDING_PAGE', 'image/png', 'grammarly.png'),
('Skillshare', 'LANDING_PAGE', 'image/png', 'skillshare.png'),
('Privacy', 'LANDING_PAGE', 'image/png', 'privacy.png'),
('Transistor', 'LANDING_PAGE', 'image/png', 'transistor.png'),
('Miruni', 'LANDING_PAGE', 'image/png', 'miruni.png'),
('Sidemail', 'LANDING_PAGE', 'image/png', 'sidemail.png'),
('Nolt', 'LANDING_PAGE', 'image/png', 'nolt.png'),
('Canny', 'LANDING_PAGE', 'image/png', 'canny.png'),
('MailPoet', 'LANDING_PAGE', 'image/png', 'mailpoet.png'),
('Marvel', 'LANDING_PAGE', 'image/png', 'marvel.png'),
('Buffer', 'LANDING_PAGE', 'image/png', 'buffer.png');
