-- Add design_system column to projects table
-- Stores per-project design system generated by AI for visual consistency across builds
ALTER TABLE projects ADD COLUMN IF NOT EXISTS design_system TEXT;
